language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.6.6
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
  - mysql
  - postgresql
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
notifications:
  slack:
    secure: UYYu1zrEkpVI3sEDEI++6CTrqpVBItPx1xI6fwA6CoJhcqQRVImj9lLTjNbIm0jvEpn+TOXMO4GCyk6s38eL/J1itCTL2tmasmt+oa9wvwcHtx+SGspFnwqPJBO/aEMWN4gZofsGTiReJ9Gn796UvNExDMLjk2nMp1paV2EsVXU=
sudo: false
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - chromium-browser
jdk:
  - openjdk8
dist: xenial
